[package]
name = "zay"
version = "0.2.0"
edition = "2024"
description = "A simple network proxy"
repository = "https://github.com/ikey4u/zay"
license = "MIT OR Apache-2.0"
build = "build.rs"

[build-dependencies]
ureq = { version = "2", default-features = false, features = ["tls"] }
flate2 = { version = "1", default-features = false, features = ["rust_backend"] }
zip = { version = "2", default-features = false, features = ["deflate"] }

[dependencies]
anyhow = "1"
axum = "0.8"
clap = { version = "4", features = ["derive"] }
ctrlc = "3.4"
dirs-next = "2"
rpassword = "7"
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls", "blocking"] }
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "net"] }
toml = "0.8"

[target.'cfg(unix)'.dependencies]
libc = "0.2"
