use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[serde(rename_all = "kebab-case")]
pub struct TunConfig {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub enable: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub device: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub stack: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub dns_hijack: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub auto_route: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub auto_detect_interface: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub mtu: Option<u32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub gso: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub gso_max_size: Option<u32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub inet6_address: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub iproute2_table_index: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub iproute2_rule_index: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub auto_redirect: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub auto_redirect_input_mark: Option<u32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub auto_redirect_output_mark: Option<u32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub auto_redirect_iproute2_fallback_rule_index: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub loopback_address: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub strict_route: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub route_address: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub route_address_set: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub route_exclude_address: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub route_exclude_address_set: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub include_interface: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub exclude_interface: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub include_uid: Option<Vec<u32>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub include_uid_range: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub exclude_uid: Option<Vec<u32>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub exclude_uid_range: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub exclude_src_port: Option<Vec<u16>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub exclude_src_port_range: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub exclude_dst_port: Option<Vec<u16>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub exclude_dst_port_range: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub include_android_user: Option<Vec<i32>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub include_package: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub exclude_package: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub include_mac_address: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub exclude_mac_address: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub endpoint_independent_nat: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub udp_timeout: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub disable_icmp_forwarding: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub file_descriptor: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub inet4_route_address: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub inet6_route_address: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub inet4_route_exclude_address: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub inet6_route_exclude_address: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub recvmsgx: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sendmsgx: Option<bool>,
}
