//! Foundational helpers corresponding to the upstream `common` package.

#[cfg(target_vendor = "apple")]
#[cfg(feature = "full")]
pub(crate) mod apple_http;
#[cfg(target_vendor = "apple")]
#[cfg(feature = "full")]
pub(crate) mod apple_tls;
#[cfg(feature = "full")]
pub mod certificate_store;
#[cfg(feature = "full")]
pub mod http;
#[cfg(feature = "full")]
pub mod json;
#[cfg(feature = "full")]
pub mod keygen;
#[cfg(target_os = "linux")]
#[cfg(feature = "full")]
pub(crate) mod ktls;
#[cfg(feature = "full")]
pub mod lifecycle;
#[cfg(feature = "full")]
pub(crate) mod neighbor;
pub mod network;
#[cfg(feature = "full")]
pub(crate) mod network_monitor;
#[cfg(feature = "full")]
pub mod ntp;
#[cfg(feature = "full")]
pub mod platform_network;
#[cfg(feature = "full")]
pub(crate) mod process;
#[cfg(feature = "full")]
pub(crate) mod quic;
#[cfg(feature = "full")]
pub mod reality;
#[cfg(feature = "full")]
pub(crate) mod reality_tls;
#[cfg(feature = "full")]
pub mod redir;
#[cfg(feature = "full")]
pub mod sniff;
#[cfg(feature = "full")]
pub(crate) mod socket;
#[cfg(feature = "full")]
pub mod stun;
#[cfg(feature = "full")]
pub(crate) mod system_proxy;
#[cfg(feature = "full")]
pub mod tls;
#[cfg(feature = "full")]
pub mod tls_spoof;
#[cfg(feature = "full")]
pub(crate) mod udp_nat;
#[cfg(feature = "full")]
pub(crate) mod utls;
#[cfg(feature = "full")]
pub(crate) mod utls_profiles;
#[cfg(feature = "full")]
pub(crate) mod utls_shaping;
#[cfg(windows)]
#[cfg(feature = "full")]
pub(crate) mod windows_tls;
