//! Validation against the schema generated by the pinned upstream source.

use std::sync::LazyLock;

use jsonschema::Validator;
use serde_json::Value;

use crate::option::ConfigError;

/// The exact schema checked into `inner/sing-box` at [`crate::UPSTREAM_REVISION`].
pub const UPSTREAM_SCHEMA_JSON: &str =
    include_str!("../../../inner/sing-box/docs/schema.json");

static VALIDATOR: LazyLock<Result<Validator, String>> = LazyLock::new(|| {
    let schema: Value =
        serde_json::from_str(UPSTREAM_SCHEMA_JSON).map_err(|error| {
            format!("invalid embedded upstream schema: {error}")
        })?;
    jsonschema::validator_for(&schema)
        .map_err(|error| format!("compile embedded upstream schema: {error}"))
});

pub fn validate(value: &Value) -> Result<(), ConfigError> {
    let validator = VALIDATOR
        .as_ref()
        .map_err(|message| ConfigError::Validation(message.clone()))?;
    let errors: Vec<String> = validator
        .iter_errors(value)
        .map(|error| {
            let path = error.instance_path().to_string();
            if path.is_empty() {
                error.to_string()
            } else {
                format!("at {path}: {error}")
            }
        })
        .collect();
    if errors.is_empty() {
        Ok(())
    } else {
        Err(ConfigError::Validation(errors.join("; ")))
    }
}

#[cfg(test)]
mod tests {
    use serde_json::json;

    use super::validate;

    #[test]
    fn validates_minimal_config() {
        validate(&json!({})).unwrap();
    }

    #[test]
    fn rejects_unknown_nested_protocol_option() {
        let error = validate(&json!({
            "outbounds": [{"type": "direct", "definitely_unknown": true}]
        }))
        .unwrap_err();
        assert!(error.to_string().contains("definitely_unknown"));
    }

    #[test]
    fn rejects_invalid_server_port_type() {
        assert!(
            validate(&json!({
                "outbounds": [{
                    "type": "socks",
                    "server": "127.0.0.1",
                    "server_port": "1080"
                }]
            }))
            .is_err()
        );
    }
}
