use std::{
    io::Write,
    path::{Path, PathBuf},
};

use anyhow::{Context, Result};
use clap::Args;

#[derive(Args, Debug)]
pub struct SystemctlCli {
    /// WebUI port (listens on 127.0.0.1)
    #[arg(long, default_value_t = 18888, value_parser = clap::value_parser!(u16).range(1..))]
    port: u16,
    /// Zay data directory (defaults to the current user's configuration directory)
    #[arg(short, long, value_name = "DIR")]
    data_dir: Option<PathBuf>,
    /// Path to zay.toml
    #[arg(short = 'c', long, value_name = "FILE")]
    config: Option<PathBuf>,
}

pub fn run(opts: SystemctlCli) -> Result<()> {
    let executable =
        std::env::current_exe().context("locating zay executable")?;
    let home = crate::settings::sudo_invoker_home()
        .or_else(dirs_next::home_dir)
        .context("locating user home directory")?;
    let (data_dir, config) = crate::settings::stack_config_paths(
        opts.data_dir.as_deref(),
        opts.config.as_deref(),
    );
    let unit = render_unit(
        &executable,
        &std::path::absolute(home)?,
        &std::path::absolute(data_dir)?,
        &std::path::absolute(config)?,
        opts.port,
    )?;
    std::io::stdout().lock().write_all(unit.as_bytes())?;
    Ok(())
}

fn render_unit(
    executable: &Path,
    home: &Path,
    data_dir: &Path,
    config: &Path,
    port: u16,
) -> Result<String> {
    let executable = quote(path_text(executable)?);
    let home_env = quote(&format!("HOME={}", path_text(home)?));
    let data_dir = quote(path_text(data_dir)?);
    let config = quote(path_text(config)?);
    Ok(format!(
        "# Zay Linux systemd service (generated by zay x systemctl)
# Run this command on the target Linux machine after installing zay at its permanent path.
# Executable, home, and configuration paths are absolute; no placeholders need replacing.
# Save this output as zay.service, then install and start it:
#   sudo install -m 644 zay.service /etc/systemd/system/zay.service
#   sudo systemctl daemon-reload
#   sudo systemctl enable --now zay
# Stop any manually started zay first to avoid port and TUN conflicts.
# View status and logs:
#   sudo systemctl status zay
#   sudo journalctl -u zay -f
# After editing zay.toml or updating the executable: sudo systemctl restart zay
# After editing this unit: sudo systemctl daemon-reload && sudo systemctl restart zay
# Stop: sudo systemctl stop zay
# Stop and disable startup at boot: sudo systemctl disable --now zay
# WebUI: http://127.0.0.1:{port}/ (local access only)
# Remote access via SSH forwarding: ssh -L {port}:127.0.0.1:{port} user@server
# The service runs as root for TUN access and never prompts for a sudo password.
# Newly generated configuration and cache files may be owned by root.

[Unit]
Description=Zay WebUI and network core
Wants=network-online.target
After=network-online.target

[Service]
Type=simple
User=root
Environment={home_env}
WorkingDirectory=/
ExecStart=:{executable} webui --data-dir {data_dir} --config {config} --listen 127.0.0.1:{port}
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
"
    ))
}

fn path_text(path: &Path) -> Result<&str> {
    path.to_str()
        .context("systemd unit paths must be valid UTF-8")
}

// Escape systemd quoting and specifiers. ExecStart's ':' prefix disables
// environment expansion, preserving literal dollars in all paths.
fn quote(text: &str) -> String {
    let mut out = String::from("\"");
    for c in text.chars() {
        match c {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            '%' => out.push_str("%%"),
            _ => out.push(c),
        }
    }
    out.push('"');
    out
}

#[cfg(test)]
mod tests {
    use clap::Parser;

    use super::*;

    #[test]
    fn systemctl_port_and_config_options() {
        #[derive(clap::Parser)]
        struct Options {
            #[command(flatten)]
            opts: SystemctlCli,
        }
        let parse = |args: &[&str]| Options::try_parse_from(args).unwrap().opts;
        assert_eq!(parse(&["systemctl"]).port, 18888);
        let opts =
            parse(&["systemctl", "--port", "3333", "--config", "custom.toml"]);
        assert_eq!(opts.port, 3333);
        assert_eq!(opts.config, Some(PathBuf::from("custom.toml")));
        for port in ["0", "65536", "abc"] {
            assert!(
                Options::try_parse_from(["systemctl", "--port", port]).is_err()
            );
        }
    }

    #[test]
    fn systemctl_command_is_linux_only() {
        use clap::CommandFactory;

        let command = crate::Cli::command();
        let experimental = command.find_subcommand("x").unwrap();
        assert_eq!(
            experimental.find_subcommand("systemctl").is_some(),
            cfg!(target_os = "linux")
        );
        assert_eq!(
            crate::Cli::try_parse_from(["zay", "x", "systemctl"]).is_ok(),
            cfg!(target_os = "linux")
        );
    }

    #[test]
    fn systemctl_unit_preserves_special_paths() {
        let unit = render_unit(
            Path::new("/opt/Zay App/zay"),
            Path::new("/home/a%u$b"),
            Path::new("/home/a%u$b/.config/zay"),
            Path::new("/tmp/a\"b\\c.toml"),
            3333,
        )
        .unwrap();
        assert!(unit.contains("Environment=\"HOME=/home/a%%u$b\""));
        assert!(unit.contains("WorkingDirectory=/"));
        assert!(unit.contains(concat!(
            "ExecStart=:\"/opt/Zay App/zay\" webui ",
            "--data-dir \"/home/a%%u$b/.config/zay\" ",
            "--config \"/tmp/a\\\"b\\\\c.toml\" --listen 127.0.0.1:3333"
        )));
    }
}
